### ISSUE TITLE
Add abitlity to deserialize properties with custom name without having change the entity

### ISSUE THREAD

**Issue by sunshinecool** [ramonhagenaars/jsons#105]
Use case: 
entity definition
```
@dataclass
class Car
    theName: str
```
external resource (json)
```
{
    'name': 'chevy'
}
```
I want to have the ability to define the json property name instead of changing my entity definition, in this case from `theName` to `name`. Is this possible today somehow? 

I think this is possible by adding custom annotations like `@JsonProperty` etc. something like this
```
@dataclass
class Car
    @propertyname('name')
    theName: str
```

**Comment by ramonhagenaars** [comment]
Hi @sunshinecool ,

There is actually a feature that allows you to do this. Check out `key_transformer` in the [api](https://jsons.readthedocs.io/en/latest/api.html). It is a keyword argument that takes a function that transforms a key name.
