### ISSUE TITLE
AttributeError on deserialization into Tuple[T, ...]

### ISSUE THREAD

**Issue by haluzpav** [ramonhagenaars/jsons#11]
When running following code

```python
from typing import Tuple
import jsons
from dataclasses import dataclass

@dataclass
class A:
    tup: Tuple[str, ...]

a = A(('abc', 'qwe', '123'))
a_ser = jsons.dump(a)
a_deser = jsons.load(a_ser, A)
```

I get exception `AttributeError: 'ellipsis' object has no attribute '__origin__'` on the last line.

I can simply use `List[str]` as type, but it would be nice to be able to deserialize into tuple of variable length.

**Comment by ramonhagenaars** [comment]
Thank you haluzpav. This issue has been resolved in [jsons 0.6.1](https://pypi.org/project/jsons/).
