### ISSUE TITLE
get_serializer returning None

### ISSUE THREAD

**Issue by davetapley** [ramonhagenaars/jsons#165]
I ran in to this issue while investigating https://github.com/spulec/freezegun/issues/448:

```py
from datetime import datetime, timezone
from jsons import dumps, get_serializer

value = datetime.now(tz=timezone.utc)

print(value.__class__)
# <class 'datetime.datetime'>

print(dumps(value))
# "2022-05-17T01:02:56.763917Z"

print(get_serializer(value))
# None
```

Am I missing something? 🤔 

https://replit.com/@jefdave/jsons-getserializer#main.py

**Comment by ramonhagenaars** [comment]
Hi @davetapley , you are providing a `datetime` instance to `get_serializer` where a `type` is expected.

Try:
```python
get_serializer(value.__class__)
```
