### ISSUE TITLE
Missing source distribution on PyPI

### ISSUE THREAD

**Issue by jochembroekhoff** [ramonhagenaars/jsons#166]
Until version 0.8.9, `jsons` has always provided a source distribution on PyPI, separate from the wheel.
Recent-ish versions don't do this anymore, even though it is conventional for most packages published on PyPI to have one (*1).

For a larger project I am working on, `jsons` is the only package that does not include a source distribution.
We are targeting a constrained custom platform for which we cannot use any wheels (or any other form of built distribution), so it would be great if future releases could actually include this variant.

(*1) "Minimally, you should create a [Source Distribution](https://packaging.python.org/en/latest/glossary/#term-Source-Distribution-or-sdist)" ([Python Packaging User Guide](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#source-distributions)).

**Comment by ramonhagenaars** [comment]
Hi @jochembroekhoff. Thank you for pointing this out, I wasn't aware of this. For the time being, you can still find the sources on Github, [under the releases](https://github.com/ramonhagenaars/jsons/releases/tag/v1.6.2).

**Comment by ramonhagenaars** [comment]
FYI: the [newest release](https://pypi.org/project/jsons/1.6.3/#files) comes with sources.

Closing this ticket.

**Comment by jochembroekhoff** [comment]
Thanks!
