### ISSUE TITLE
Should it be possible to discard None-fields from dump?

### ISSUE THREAD

**Issue by casparjespersen** [ramonhagenaars/jsons#19]
I'd like to throw in the idea that it should be possible to have the option of omitting a field from the dump, if its value is `None`. Intended use:

```
@dataclass
class Foo():
    foo: int
    bar: bool = None

jsons.dump(Foo(1))                          #output: {"foo": 1, "bar": None}
jsons.dump(Foo(1), omit_none=True)          #output: {"foo": 1}
jsons.dump(Foo(1, True))                    #output: {"foo": 1, "bar": True}
```

Maybe this is already possible using a serializer?

**Comment by ramonhagenaars** [comment]
Hi Casparjespersen.

Yes, that is possible already by using:

```python
jsons.dump(Foo(1), strip_nulls=True)
```

Have you found the (new) [documentation](https://github.com/ramonhagenaars/jsons/blob/master/API_DOCUMENTATION.rst#dump) page? Or do you think that the documentation needs to be improved? :-)

**Comment by casparjespersen** [comment]
Awesome! I was unaware of the documentation page. I think it's quite comprehensive and very well worked through. Thank you for your work on this module :-)
