### ISSUE TITLE
Should named tuple be serialized as tuple or like dict

### ISSUE THREAD

**Issue by cypreess** [ramonhagenaars/jsons#21]
Similarly to #18 I start being biased towards thinking that because of "readability counts" NamedTuples should be expressed like to dicts. The whole point of naming tuple positions is because of poor readability of tuples. Then we totally drop it on serialization level when we already decided we go for readability.

**Comment by ramonhagenaars** [comment]
Good point. As for deserialization, both arrays and dicts should be deserializable to a namedtuple.

**Comment by cypreess** [comment]
When could we expect this feature to be implemented?

**Comment by ramonhagenaars** [comment]
This will be the next minor update, so ``0.8.2``. Expect it anytime soon. :-)

**Comment by ramonhagenaars** [comment]
This issue has been solved in [0.8.2](https://pypi.org/project/jsons/0.8.2/).
