### ISSUE TITLE
Verbosity dump does not reconstruct with correct classes

### ISSUE THREAD

**Issue by casparjespersen** [ramonhagenaars/jsons#24]
Related to [this feature request](https://github.com/ramonhagenaars/jsons/issues/14), I wanted to try it out, but I can not mange to re-construct the objects given the metadata structure. Check out this script:

```
import jsons
from dataclasses import dataclass

@dataclass
class BarBase():
    pass

@dataclass
class BarA(BarBase):
    a: int

@dataclass
class BarB(BarBase):
    b: int

@dataclass
class Foo():
    bar: BarBase

if __name__ == "__main__":
    f = Foo(bar=BarA(a=5))
    d = jsons.dump(f, verbose=True)
    o = jsons.load(d)
    print("original:", f)
    print("dump:", d)
    print("reconstructed:", o)
```

It gives the following output (Python 3.7.2 and `jsons==0.8.0`):
```
original: Foo(bar=BarA(a=5))
dump: {'bar': {'a': 5}, '-meta': {'classes': {'/bar': '__main__.BarA', '/': '__main__.Foo'}, 'dump_time': '2019-03-20T12:55:38Z'}}
reconstructed: Foo(bar=BarBase())
```

It appears that the serialization is done properly, but that the re-construction does not take the classes into account?

**Comment by ramonhagenaars** [comment]
Thanks casparjespersen. This was a sloppy bug; loading a verbose dict only worked on the upper class; not recursively.

This bug has been fixed in [`0.8.1`](https://pypi.org/project/jsons/0.8.1/).
