### ISSUE TITLE
[Question] mypy_extensions.TypedDict

### ISSUE THREAD

**Issue by jmolinski** [ramonhagenaars/jsons#25]
Hello!

Does the author consider adding support for the `TypedDict` from `mypy_extensions` in the future? 
TypedDict is extremely helpful for type hinting and code completion and its syntax is very concise. 
A detailed description can be found [here](https://mypy.readthedocs.io/en/latest/more_types.html#typeddict). It is also likely that it will be found in the standard library `typing` module in the future versions of Python: https://github.com/python/mypy/issues/5288

As a downside, this would introduce a dependency - `mypy_extensions`. A solution to that would be making the dependency optional the same way for example `Flask` has an optional dependency `SimpleJSON` and only uses it if this package is installed.

**Comment by ramonhagenaars** [comment]
Hi jmolinski, thanks for your suggestion.

I think it is worth considering. What keeps me from adding this feature too soon, is that it is still marked as experimental.

I agree with you that if this feature is to be incorporated at all, it should be made optional to keep the dependencies minimized.

**Comment by cypreess** [comment]
I personally think we should focus on supporting things from the standard library -- `typing`. TypedDict sounds to me like some ugly hack for those who did not get used to using data classes as named tuples for declaring types. But I might be very wrong me, please correct if I am with some practical use cases.

**Comment by jmolinski** [comment]
In my view, the main advantages are runtime compatibility with ordinary dict and anonymous/inline use.

**Comment by jmolinski** [comment]
After consideration, I think this should be implemented after `TypedDict` will have been incorporated into the stdlib `typing` module.
