### ISSUE TITLE
strip_properties does not work on nested objects

### ISSUE THREAD

**Issue by haluzpav** [ramonhagenaars/jsons#3]
Parameter `strip_properties` of `dump` function works only for top-level object. `@property` of nested objects are always included in json. See my gist example:

https://gist.github.com/haluzpav/b578dad460cb3670d55305dc65d9d2bf

Is there a way to also strip properties of nested objects?

**Comment by ramonhagenaars** [comment]
This has been fixed in version `0.6.0`.
