### ISSUE TITLE
strip_properties removes also privates

### ISSUE THREAD

**Issue by haluzpav** [ramonhagenaars/jsons#4]
As in title, `strip_privates` gets "over-written" by `strip_properties`. Example:

https://gist.github.com/haluzpav/628477bdeee8e33ed40e07c2b786c2dd

Kinda related to previous issue #3.

**Comment by ramonhagenaars** [comment]
Thank you haluzpav, for pointing this out and creating a pull request! I will review your pull request shortly.

**Comment by ramonhagenaars** [comment]
This has been fixed in version `0.6.0`.
