### ISSUE TITLE
Support for UUID type

### ISSUE THREAD

**Issue by ahmetkucuk** [ramonhagenaars/jsons#57]
Simply transform as follows:
Serializer: `uuid_str = str(uuid)`
Deserializer: `uuid = uuid.UUID(uuid_str)`

I am willing to implement if there is a desire to have this in the library.

**Comment by ramonhagenaars** [comment]
Hi ahmetkucuk. 

Since it is a class in the standard lib and since the implementation seems to be very light, I don't see why it shouldn't be added. I would gladly review your pull request.

**Comment by ramonhagenaars** [comment]
Thanks again ahmetkucuk. This issue has been deployed in [``0.8.9``](https://pypi.org/project/jsons/).
