### ISSUE TITLE
Inconsistent get_class_name

### ISSUE THREAD

**Issue by haluzpav** [ramonhagenaars/jsons#81]
```python
from datetime import datetime

import jsons
from jsons._common_impl import get_class_name

print(get_class_name(datetime))
# >>> datetime

jsons.dumps(datetime.utcnow())

print(get_class_name(datetime))
# >>> datetime.datetime
```

It is caused by the fact that classes are automatically announced during dumping, in fully qualified form. If a class is announced, it's name in `get_class_name` is taken directly from `_announced_classes`, without taking into account `fully_qualified: bool` argument.

**Comment by ramonhagenaars** [comment]
Thanks for figuring this out and well found! I'll fix this one in ``v1.1.1``.
