### ISSUE TITLE
How to bypass self as a class attribute name error? __init__() got multiple values for argument '__dataclass_self__'

### ISSUE THREAD

**Issue by aadamvanko** [ramonhagenaars/jsons#83]
Hi, I have a JSON containing objects that contain field named `self` and it crashes due to this error: `jsons.exceptions.DeserializationError: Could not deserialize value "{'self': 'api/v3/message/0'}" into "__main__.MyClass". __init__() got multiple values for argument '__dataclass_self__'`. I understand the error and the cause, but is there a way how to bypass this limition other than renaming the field in the original JSON string before deserializing and also the class attribute? Thanks

Regards,
Adam

Example code ([live demo here](https://repl.it/repls/HumiliatingGloriousCache)):
```python
import jsons
import dataclasses


@dataclasses.dataclass
class MyClass:
    self: str


myclassObj = jsons.loads('''{"self":"api/v3/message/0"}''', MyClass)
print(myclassObj)
```

**Comment by ramonhagenaars** [comment]
Hi aadamvanko.

First of all, I would strongly advise you not to use `self` in Python for anything other than the first parameter of a method. It is against the convention and it is not a descriptive name for a variable either.

`jsons` will fail to deserialize into a dataclass with that attribute. However, you could tell `jsons` to deserialize an attribute into an attribute with a different name using the `key_transformer` argument.

Here's how:
```python
import jsons
import dataclasses


>>> @dataclasses.dataclass
... class MyClass:
...    self_: str  # Note the underscore


>>> myclassObj = jsons.loads('''{"self":"api/v3/message/0"}''', MyClass, key_transformer=lambda key: 'self_' if key == 'self' else key)
MyClass(self_='api/v3/message/0')
```

The other way round works as well:
```python
>>> jsons.dumps(MyClass('something'), key_transformer=lambda key: 'self' if key == 'self_' else key)
'{"self": "something"}'
```

Regards,
Ramon

**Comment by aadamvanko** [comment]
Thanks for the advice, the JSON is from the external service, so I have no control over it's naming. The solution you have proposed is an viable option. Thanks for the help.
