### ISSUE TITLE
How can I map a JSON field to a differently-named class field?

### ISSUE THREAD

**Issue by davemx** [ramonhagenaars/jsons#84]
I have JSON that looks like this:

```json
{
  "st": 3,
  "s": -7.0
}
```

And a class that I'd like to look like:

```python
@dataclass
class Pick:
    stake: int
    spread: float
```

I'd like to map the `st` field to `stake` and `s` to `spread`. In Marshmallow, you can specify an alternate `data_key`. Is there a way to do this in JSONS? Like a per-field key transformer or decoration or anything?

Thanks,
Dave

**Comment by ramonhagenaars** [comment]
Hi Dave.

Use the `key_transformer` attribute. It takes a function that accepts a string and returns a string.

Example:
```python
@dataclass
class Pick:
    stake: int
    spread: float


d = {
  "st": 3,
  "s": -7.0
}
key_mapping = {
  "st": "stake",
  "s": "spread"
}
jsons.load(d, cls=Pick, key_transformer=lambda key: key_mapping[key])
```

**Comment by davemx** [comment]
Thank you!
