### ISSUE TITLE
Add py.typed to package so that type hints work with mypy

### ISSUE THREAD

**Issue by kazimuth** [ramonhagenaars/jsons#88]
See [PEP 561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information):

> In order to make packaging and distributing type information as simple and easy as possible, packaging and distribution is done through existing frameworks.
> Package maintainers who wish to support type checking of their code MUST add a marker file named py.typed to their package supporting typing. This marker applies recursively: if a top-level package includes it, all its sub-packages MUST support type checking as well. To have this file installed with the package, maintainers can use existing packaging options such as package_data in distutils, shown below.
> Distutils option example:
> ```
>   setup(
>    ...,
>    package_data = {
>        'foopkg': ['py.typed'],
>    },
>    ...,
>    )
> ```

**Comment by ramonhagenaars** [comment]
Thank you Kazimuth. I'm marking this issue as duplicate as #71 describes pretty much the same.
