### ISSUE TITLE
dump() / load() APIs are confusingly named

### ISSUE THREAD

**Issue by kazimuth** [ramonhagenaars/jsons#89]
In the standard `json` module, `dump()` and `load()` dump bytes to a file. In `jsons`, they instead return objects. This is potentially confusing behavior, especially if the file object turns out to be serializeable, since the function call might then appear to silently fail. Not sure if this can be easily changed, though.

**Comment by ramonhagenaars** [comment]
I see your point Kazimuth. The names were chosen to make the library blend into the builtin `json` library. Right now, as the library is growing, I'd rather not change them anymore. You can still alias them yourself of course.
