### ISSUE TITLE
Mention strip_* options in README

### ISSUE THREAD

**Issue by haluzpav** [ramonhagenaars/jsons#9]
They are too useful to be left out. :)

**Comment by ramonhagenaars** [comment]
You are right. Moreover, the documentation as a whole can really use an update, I'm on that. It's a cumbersome task, so it may take some time.

**Comment by ramonhagenaars** [comment]
The documentation can be found [here](https://github.com/ramonhagenaars/jsons/blob/master/API_DOCUMENTATION.rst).
