### ISSUE TITLE
_field_types of typing.NamedTuple has been deprecated and will be removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [ramonhagenaars/jsons#95]
https://github.com/ramonhagenaars/jsons/blob/e335fd5ebc465b523cf153675ad2eeafbc37b5fb/jsons/deserializers/default_tuple.py#L56

https://docs.python.org/3/whatsnew/3.8.html#deprecated

```
The typing.NamedTuple class has deprecated the _field_types attribute in favor of the 
__annotations__ attribute which has the same information. 
(Contributed by Raymond Hettinger in bpo-36320.)
```

**Comment by ramonhagenaars** [comment]
Hi @tirkarthi. I see you also created a pull request for this: thank you! I'll address it soon.
